Repository NHSDigital/dtos-cohort-manager, pull requests merged in 2025-04, with the labels that each got.

#903 test: DTOSS-7806 Update ReceiveCaasFileHelper tests
  application/CohortManager/src/Functions/Functions.sln
  tests/UnitTests/SharedTests/ReceiveCaasFileHelperTests/ReceiveCaasFileHelperTests.cs
  tests/UnitTests/SharedTests/ReceiveCaasFileHelperTests/ReceiveCaasFileHelperTests.csproj
Labels: test coverage

#894 fix: now allows for name prefixs of 'R.RV', R.HN
  application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/namePrefixRules.json
  tests/UnitTests/TransformDataServiceTests/TransformDataServiceTests/TransformDataServiceTests.cs
Labels: bug

#853 feat: add blocked flag column to participant management table
  application/CohortManager/Set-up/database/create_statement.sql
  application/CohortManager/src/Functions/Shared/Model/EFModels/ParticipantManagement.cs
  application/CohortManager/src/Functions/Shared/Model/Participant.cs
Labels: DO NOT MERGE

#890 chore: Remove Docker Examples
  scripts/docker/examples/python/.tool-versions.example
  scripts/docker/examples/python/Dockerfile
  scripts/docker/examples/python/Dockerfile.effective
  scripts/docker/examples/python/VERSION
  scripts/docker/examples/python/assets/hello_world/app.py
  scripts/docker/examples/python/assets/hello_world/requirements.txt
  scripts/docker/examples/python/tests/goss.yaml
Labels: Remove unused methods

#924 fix: pass screening service name to exception handler
  application/CohortManager/src/Functions/CohortDistributionServices/TransformDataService/TransformDataService.cs
Labels: bug

#856 fix: increasing durable function test coverage
  application/CohortManager/src/Functions/DemographicServices/DemographicDurableFunction/DurableDemographicFunction.cs
  tests/UnitTests/DurableDemographicTests/DurableDemographicTests.cs
  tests/UnitTests/ScreeningDataServicesTests/MarkParticipantAsIneligibleTests/MarkParticipantAsIneligibleTests.cs
Labels: test coverage

#905 feat: DTOSS-8376 & 8377 add nems subscription table and service
  application/CohortManager/Set-up/database/create_statement.sql
  application/CohortManager/compose.data-services.yaml
  application/CohortManager/src/Functions/Functions.sln
  application/CohortManager/src/Functions/Shared/DataServices.Database/DataServicesContext.cs
  application/CohortManager/src/Functions/Shared/Model/EFModels/NemsSubscription.cs
  application/CohortManager/src/Functions/screeningDataServices/NemsSubscriptionDataService/.vscode/extensions.json
  application/CohortManager/src/Functions/screeningDataServices/NemsSubscriptionDataService/Dockerfile
  application/CohortManager/src/Functions/screeningDataServices/NemsSubscriptionDataService/HealthCheckFunction.cs
  application/CohortManager/src/Functions/screeningDataServices/NemsSubscriptionDataService/NemsSubscriptionDataService.cs
  application/CohortManager/src/Functions/screeningDataServices/NemsSubscriptionDataService/NemsSubscriptionDataService.csproj
  application/CohortManager/src/Functions/screeningDataServices/NemsSubscriptionDataService/Program.cs
  application/CohortManager/src/Functions/screeningDataServices/NemsSubscriptionDataService/Properties/launchSettings.json
  application/CohortManager/src/Functions/screeningDataServices/NemsSubscriptionDataService/host.json
  infrastructure/tf-core/environments/development.tfvars
  infrastructure/tf-core/environments/devtest.tfvars
  tests/IntegrationTests/integration.csproj
  tests/UnitTests/DataServiceTests/DataServiceTests.csproj
  tests/UnitTests/DataServiceTests/NemsSubscriptionDataServiceTests.cs
Labels: NEMS
